#!/usr/bin/env python3
"""
build_single_file.py — fold src/ into one dist/Code.gs that can be pasted by hand.

clasp is the normal way in. When there is no terminal to run it from — someone
setting this up from a phone — the fallback is pasting into the Apps Script
editor, and three files is three chances to paste the wrong thing into the wrong
place. This produces one file that carries the UI inside it.

The manifest is deliberately not part of the output: Apps Script infers the
oauth scopes it needs, and the web app's "execute as" and "who has access" come
from the Deploy dialog, not from appsscript.json. So the single file is
genuinely all that has to be pasted.

Usage:
    python build_single_file.py
"""

import pathlib
import re
import sys

SRC = pathlib.Path('src')
OUT = pathlib.Path('dist/Code.gs')

BANNER = """// ============================================================
//  Shelf Count — single-file build. DO NOT EDIT THIS FILE.
// ============================================================
//  Generated from src/Code.gs + src/Index.html by
//  build_single_file.py. Edit those and rebuild; edits made here
//  are lost on the next build.
//
//  Paste this whole file over Code.gs in the Apps Script editor.
//  Nothing else needs pasting — the UI is inlined below, and the
//  manifest is inferred by Apps Script.
// ============================================================

"""


def main():
    code = (SRC / 'Code.gs').read_text(encoding='utf-8')
    html = (SRC / 'Index.html').read_text(encoding='utf-8')

    # The HTML goes into a template literal verbatim. That is only safe while it
    # contains none of the three things a template literal reacts to, so this is
    # checked rather than assumed — an edit upstream would otherwise produce a
    # file that is subtly broken instead of obviously broken.
    hazards = {'backtick': '`', 'placeholder': '${', 'backslash': '\\'}
    found = {name: html.count(ch) for name, ch in hazards.items() if ch in html}
    if found:
        sys.exit(
            'src/Index.html now contains %s, which a template literal would '
            'reinterpret. Escape them here before inlining.' % found
        )

    # createHtmlOutputFromFile needs a separate Index file; the inlined build
    # serves the string instead.
    if "createHtmlOutputFromFile('Index')" not in code:
        sys.exit('src/Code.gs no longer serves Index — update this script.')
    code = code.replace(
        "HtmlService.createHtmlOutputFromFile('Index')",
        'HtmlService.createHtmlOutput(INDEX_HTML)'
    )

    out = BANNER + code.rstrip() + '\n\n' + (
        '// ── The page, inlined ──────────────────────────────────────\n'
        'const INDEX_HTML = `' + html.rstrip() + '`;\n'
    )

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(out, encoding='utf-8')
    print('%s — %d lines, %.1f KB' % (OUT, out.count('\n') + 1, len(out.encode()) / 1024))


if __name__ == '__main__':
    main()
